server: 
  port: 9008
spring: 
  application:  
    name: huahua-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.2.21.128:3306/huahua_user?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true

  redis:
    host: 10.2.21.128
    port: 6379

  rabbitmq:
    host: 10.2.21.128
    username: guest
    password: gaoxuanqi
#jwt.config
jwt:
  config:
    key: huahuaCommunity
    ###过期时间
    ttl: 3600000
#注册到eureka服务中
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/
  instance:
    prefer-ip-address: true


