server:
  port: 9011
spring:
  application:
    name: huahua-manager

#注册到eureka服务中
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/
  instance:
    prefer-ip-address: true

zuul:
  routes:
    huahua-gathering: #活动
     path: /gathering/** #配置请求URL的请求规则
     serviceId: huahua-gathering #指定Eureka注册中心中的服务id
    huahua-article: #文章
     path: /article/** #配置请求URL的请求规则
     serviceId: huahua-article #指定Eureka注册中心中的服务id
    huahua-base: #基础
     path: /base/** #配置请求URL的请求规则
     serviceId: huahua-base #指定Eureka注册中心中的服务id
    huahua-friend: #交友
     path: /friend/** #配置请求URL的请求规则
     serviceId: huahua-friend #指定Eureka注册中心中的服务id
    huahua-qa: #问答
     path: /qa/** #配置请求URL的请求规则
     serviceId: huahua-qa #指定Eureka注册中心中的服务id
    huahua-recruit: #招聘
     path: /recruit/** #配置请求URL的请求规则
     serviceId: huahua-recruit #指定Eureka注册中心中的服务id
    huahua-spit: #吐槽
     path: /spit/** #配置请求URL的请求规则
     serviceId: huahua-spit #指定Eureka注册中心中的服务id
    huahua-user: #用户
     path: /user/** #配置请求URL的请求规则
     serviceId: huahua-user #指定Eureka注册中心中的服务id

jwt:
  config:
    key: huahuaCommunity
    ###过期时间
    ttl: 3600000
